server:
  port: 9060
spring:
  application:
    name: REGISTER-SERVICE

  datasource:
     driver-class: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/netflix
     username: postgres
     password: postgres

  sql:
    init:
      mode: always
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

 